tilemill-project/tilemill

README.md

The git: protocol doesn't work with my git client.  This URL works better: https://github.com/mapbox/tilemill.git

Updating clone instructions to a readable URL

---

_layouts/docs.html

Adds a banner to all TileMill docs pages with a link to Mapbox Studio.
cc @alianthes @katydecorah

Add warning banner to TileMill docs

---

_layouts/docs.html

It was linking to Mapbox Studio, now links to Mapbox Studio Classic. cc @katydecorah

Update warning banner to include link to Mapbox Studio Classic

---

package.json

`npm test` passes, and @springmeyer did testing in mapbox/carto#440

Upgrade to carto 0.16.0

---

models/Project.server.bones
package.json

* Lets `project.mml` and `PROJECTNAME.mml` be read as YAML
* Checks `project.yml` and `PROJECTNAME.yml` in addition to the above two filenames
This is a "soft" conversion to YAML: It only supports it on input, and it will still write `project.mml` as JSON.
It doesn't depend on #2551, but they are related as anyone using YAML files will need Carto 0.16.0 on the server to convert to XML

Add YAML support

---

package.json

Fixes a regression with the colour mix function.
Fixes a regression with colour math.

upgrade carto to 0.16.2

---

README.md

Currently points to `mapbox` repo for cloning tilemill. Updated to `tilemill-project`

update install instruction

---

assets/css/style.css
templates/Projects._
views/Projects.bones

Added an optional information icon to projects that have a description.
On mouseover it will replace the project title and the update date with the description.
On mouseleave returns to the previous state.
Finally found the time to work on this after a few months.
Issue: for project descriptions longer than two lines it will cut the text. CSS ellipsis will only work on one line text. If there is interest in integrating this solution on the project I will research a solution without requiring further integration of jQuery plugins (which was the easiest solution I found).

Optional project description

---

_posts/docs/guides/0203-01-01-osm-bright-mac-quickstart.md

Hi,
Here's a small doc update on the OSX guide to clarify where the shape files should go.
The documentation states that it should be put in the shp directory in the osm-bright folder but what is meant is the mapbox-osm-bright-* folder (ie. the root project folder). Also the OSM Bright repo does not contain a shp folder so we update the doc to reflect this.

Documentation: clarify where the shapefiles need to go

---

README.md
package.json

Since `request` updated its dependencies they're now using ES6 features that are not compatible with tilemill's engines node 0.8.x or 0.10.x. This PR fixes the `request` dependency to `2.81.0` to avoid this conflict. 
I also updated the README.md to reflect that the default application that will run is the Desktop app, and how to run the web server version.

Fix bugs based on versions and make instructions clearer

---

README.md

Additional updates to README to be consistent with TileOven status, as well as latest status of TIleMill.
- Updated URLs to point to TileMill instead of TileOven
- Updated installation instructions
- Added links to previous binaries

Update README.md for TileOven merge

---

package.json
test/abilities.test.js
test/config.test.js
test/datasource.test.js
test/duplicate_module.test.js
test/export.test.js
test/project.test.js
test/support/start.js
test/tile.test.js

Unit tests are all passing now, updated a few things:
- regex fix on a couple
- added header of 'content-length' on DELETE calls
Fixes issue #2644

Fixes issue 2644

---

package-lock.json
package.json

- Update semver from 4.1.0 to 4.3.2
- Update jquery from 2.1.0 to 3.3.1
- Update express from 2.5.11 to 3.11.0
Mocha tests all passed. Manually tested in app as well.

Fix security vulnerabilities from Github

---

package-lock.json
package.json
servers/Route.bones

Issue #2658. There was no more support for the browser version of semver (build in <v5.0.0). It was being included in Route.bones for use on the browser but never being used in the browser so I removed semver from Route.bones. Everything seems to work OK without it being there.

Updating semver from 5.0.0 to 5.6.0.

---

package-lock.json
package.json

Fixes #2636 
- Update package.json dependency to mapnik v3.7.2.
- No issues found, no fixes required.

Update mapnik to v3.7.2

---

commands/export.bones
index.js
package-lock.json
package.json

Issue #2691: Updated tilelive-mapnik to the mapbox scope and to v1.0.0. Also updated mapnik to ~3.7.2 so that it matches to tilelive-mapnik (to be safe) since we can only have one version of mapnik.

Updated tilelive-mapnik to the mapbox scope and to v1.0.0.

---

package-lock.json
package.json

Issue #2685: Upgrading to version of bones that suppresses the irritating warnings during mocha tests.

Upgrading bones version.

---

commands/core.bones
lib/gitutil.js
test/abilities.test.js

Update to how the unique version is created and tested to account for the fact that git will return different tag formats depending on whether there have been commits after the tag creation or not.

Update to how the unique version is created and tested

---

Dockerfile

As I read on #2748 there was originally a startdocker.sh file that was replaced with a CMD instruction. 
However, on the Dockerfile build we still have a RUN instruction that execute `chmod 777 starddtdocker.sh` 
This result in an error when you try to build the image: 
` chmod: cannot access 'starddtdocker.sh': No such file or directory`
I fix it by deleting the not used instruction anymore.

Fix Dockerfile RUN chmod command on missing file

---

package.json

Behind a corporate firewall, sometimes fetching packages via ssh (git) does not work while via https does.

package.json: substituted git:// with https://

---

docker-compose.yml

in order to start the docker stack on an apple m1 cpu device it is necessary to set the platform attribute - otherwise the build will fail with this error:
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/usr/src/app/node_modules/mapnik/lib/binding' (1)

force amd64 in docker-compose to support m1 cpu
